### ISSUE TITLE
error message : Unexpected token: punc ())

### ISSUE THREAD

**Issue by maruilian11** [PeterDaveHello/web-minify-helper#10]
when I use `minify.sh` to minify [this lib](https://www.npmjs.com/package/l20n) (`dist/bundle/web/l20n.js`)
it display this

```
// Error: Unexpected token: punc ())
```

but I didn't find `punc` in `l20n.js`.

**Comment by PeterDaveHello** [comment]
Please make sure it's really a bug, and report to `i20n` or `uglify-js`, depends on who is in charge of the problem, this project is jut a wrapper, have nothing to do with that error.
