### ISSUE TITLE
CSS minified output gives html with 301 Moved Permanently

### ISSUE THREAD

**Issue by nbkhope** [PeterDaveHello/web-minify-helper#18]
I tried using the script to minify a css file, but the output was the following:

```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

First, I went to the directory where my files are. Then, I ran the script ~/some/where/minify.sh using Bash v4.4.12.

**Comment by PeterDaveHello** [comment]
I think it's fixed in #19 by @nwholloway, thank you both!
